### ISSUE TITLE
Decrease complexity of LdesClient nifi processor

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#12]
we should decrease the complexity of this method

_Originally posted by @Tomvbe in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/11#discussion_r1114841871_

**Comment by Yalz** [comment]
to also take a look at destroyDb method

**Comment by Yalz** [comment]
Since there is an active refactor of Ldes Client ongoing, this ticket will be closed as part of it. 
Since this code will no longer exist in the new version
