### ISSUE TITLE
RDF4J repo materialization processor module test too slow

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-Linked-Data-Interactions#131]
Whilst building the project, it was noticeable that the rdf4j-repository-materialisation-processor module takes 48(!)s to build whilst only containing one test.

Let's reduce this.. (by a multitude of 10 preferably) 

**### Result of local maven build:**

[INFO] linked-data-interactions ........................... SUCCESS [  0.988 s]
[INFO] ldi-api ............................................ SUCCESS [  4.497 s]
[INFO] ldi-core ........................................... SUCCESS [  0.405 s]
[INFO] sparql-construct ................................... SUCCESS [  2.237 s]
[INFO] ldes-client ........................................ SUCCESS [  0.303 s]
[INFO] request-executor ................................... SUCCESS [ 13.642 s]
[INFO] starting-node ...................................... SUCCESS [  5.080 s]
[INFO] tree-node-fetcher .................................. SUCCESS [  5.526 s]
[INFO] tree-node-supplier ................................. SUCCESS [ 12.224 s]
[INFO] version-object-creator ............................. SUCCESS [  3.557 s]
[INFO] version-materialiser ............................... SUCCESS [  2.482 s]
[INFO] rdf-adapter ........................................ SUCCESS [  3.302 s]
[INFO] ngsiv2-to-ld-adapter ............................... SUCCESS [  5.855 s]
[INFO] geojson-to-wkt ..................................... SUCCESS [  4.400 s]
[INFO] ldi-orchestrator ................................... SUCCESS [  0.052 s]
[INFO] ldi-common ......................................... SUCCESS [  1.636 s]
[INFO] ldio-connectors .................................... SUCCESS [  4.726 s]
[INFO] ldio-http-in ....................................... SUCCESS [  8.939 s]
[INFO] ldio-ldes-client ................................... SUCCESS [  7.889 s]
[INFO] ldio-sparql-construct .............................. SUCCESS [  3.487 s]
[INFO] ldio-version-object-creator ........................ SUCCESS [  3.567 s]
[INFO] ldio-version-materialiser .......................... SUCCESS [  4.199 s]
[INFO] ldio-http-out ...................................... SUCCESS [  5.221 s]
[INFO] ldio-console-out ................................... SUCCESS [  5.229 s]
[INFO] ldio-application ................................... SUCCESS [ 10.626 s]
[INFO] ldio-http-in-poller ................................ SUCCESS [ 16.306 s]
[INFO] ldio-rdf-adapter ................................... SUCCESS [  3.547 s]
[INFO] ldio-ngsiv2-to-ld-adapter .......................... SUCCESS [  3.419 s]
[INFO] ldio-geojson-to-wkt ................................ SUCCESS [  5.389 s]
[INFO] ldio-kafka-out ..................................... SUCCESS [ 10.516 s]
[INFO] ldio-kakfa-in ...................................... SUCCESS [  7.080 s]
[INFO] ldio-integration ................................... SUCCESS [  6.557 s]
[INFO] ldi-nifi ........................................... SUCCESS [  0.764 s]
[INFO] ldi-nifi-common .................................... SUCCESS [  7.120 s]
[INFO] ldi-nifi-processors ................................ SUCCESS [  0.144 s]
[INFO] create-version-object-processor .................... SUCCESS [  5.901 s]
[INFO] ldes-client-processor .............................. SUCCESS [ 10.968 s]
[INFO] sparql-interactions-processor ...................... SUCCESS [  3.736 s]
[INFO] version-materialisation-processor .................. SUCCESS [  3.646 s]
[INFO] ngsiv2-to-ld-processor ............................. SUCCESS [  4.780 s]
[INFO] rdf4j-repository-materialisation-processor ......... SUCCESS [ 48.211 s]
[INFO] geojson-to-wkt-processor ........................... SUCCESS [  5.132 s]

**Comment by sverholen** [comment]
Speed issue fixed by explicitly closing the repository connections.
