### ISSUE TITLE
LdesClientRunner FAILURE

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#152]
**Prerequisites:**

Test plan: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/020.client-pause-and-resume
Tag provided by @rorlic  for sprint 24.
ghcr.io/informatievlaanderen/ldi-orchestrator:20230407T130529

- LDI_WORKBENCH_NIFI_TAG=20230407T130526
- LDI_ORCHESTRATOR_TAG=20230407T130529
- LDES_SERVER_TAG=20230407T1308
- LDES_WORKBENCH_NIFI_TAG=20230214T123440

**Scenario:**
1. Follow the steps documented in https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/020.client-pause-and-resume.
2. Till execute` docker compose --env-file .env up ldio-workflow -d`

**Current result:**

**_2023-04-18 13:27:53 2023-04-18T11:27:53.652Z ERROR 1 --- [pool-4-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : opening db: 'database.db': Permission denied
2023-04-18 13:27:53 2023-04-18T11:27:53.653Z ERROR 1 --- [pool-4-thread-1] b.v.i.ldes.ldio.LdesClientRunner         : LdesClientRunner FAILURE_**

Full docker logs: [ldesclient.txt](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11261222/ldesclient.txt)

**Expected result:**
There should be no error in the log

**Comment by rorlic** [comment]
I also noticed this.
Please create a folder in the docker image to hold the LDIO,
Change the working directory there (WORKDIR).
Provide user ldes with R/W to this folder.

**Comment by xdxxxdx** [comment]
Wait for the fix of : https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/175 to validate current case.

**Comment by xdxxxdx** [comment]
Validated on ghcr.io/informatievlaanderen/ldi-orchestrator:20230508T085639
with E2E tag: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/937e069594828f84154032ebb05485323626b813
