### ISSUE TITLE
CreateVersionObjectProcessor performance issue

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#19]
The processor is a bottleneck in nifi workflows as it can barely process 3.000 flowfiles in 2 minutes. 

![image](https://user-images.githubusercontent.com/34196062/222117058-301792cb-0b0b-471c-af28-3b58742b86e6.png)

**Comment by Yalz** [comment]
To be verified with new version of CreateVersionProcessor

**Comment by Tomvbe** [comment]
Closing this issue. The CreateVersionObjectProcessor was the bottleneck in the nifi flow as this was the only/first processor where the flowfiles were parsed to Jena Models. This is not an issue in LDIO because the interface of the transformer requires a model to start from.
