### ISSUE TITLE
Cypress automated test failed - 020.client-pause-and-resume - NIFI component, LDES Client doesn't synchronize ldes members

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#242]
**Describe the bug**
E2E repo tag:  7759a0450676cbc35f51567bbc58cdfbf6bf9c4a
Sprint 30 Tag: [ldes/ldi-workbench-nifi:1.2.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags)

**To Reproduce**
1.Inside the directory of the E2E Repo, run `npm test -- -e tags="@test-020" `

**Current behavior**
Test Failed. 
[020.zip](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11958904/020.zip)

- [nifi-workflow.json](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/020.client-pause-and-resume/nifi-workflow.json) is uploaded to the NIFI, and started.
- Client doesn't synchronize anything from Simulator to the Sink => Test failed. (Tried Start it manually, same result)

**Expected behavior**
Test Pass.

**Additional context**
System: Windows 11 + WSL2 + Git Bash
Please feel free move the case to E2E repo if it is a configuration issue.

**Comment by Yalz** [comment]
As of now, test 020 is green. Our apologies for not tackling the issue sooner
