### ISSUE TITLE
Sprint30 ldi-orchestrator:1.2.0-SNAPSHOT fails E2E test 014.workbench-ngsi-v2-to-ngsi-ld

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#244]
**Describe the bug**
When running the Cypress tests, ldi-orchestrator:1.2.0-SNAPSHOT fails tests: 
 014.workbench-ngsi-v2-to-ngsi-ld, 017.ldio-workbench-ngsi-v2-to-oslo and 030.server-allow-multi-collection with the same error.

**To Reproduce**
1. Go to the directory of E2E repo
2.  Run `npm test -- -e tags="@test-014 and @ldio"`. 

**Current behavior**
Test failed: 
[014.zip](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11966101/014.zip)

**Expected behavior**
Test pass

**Desktop (please complete the following information):**
 - OS: Windows 11 + WSL2 + Git bash
 
**Additional context**
- This issue only happens for the LDIO solution (NIFI works perfectly).
- This issue only occurs on the ldi-orchestrator:1.2.0-SNAPSHOT (ldi-orchestrator:1.1.0-SNAPSHOT passes the test), therefore I put this issue in the current repo.
- I tried to run the test 030 and 014 manually, but I cannot identify why the test failed. Please feel free to leave a comment.

**Comment by Yalz** [comment]
Closed since Test 14 is now successful
