### ISSUE TITLE
Elaborate RDF Adapter

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-Linked-Data-Interactions#276]
### Discussed in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/discussions/247

<div type='discussions-op-text'>

<sup>Originally posted by **xdxxxdx** July  7, 2023</sup>
https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/core/ldi-adapters/rdf-adapter

`As the most basic Adapter of the LDI Core Building Blocks, the RDF Adapter will take in an RDF string and convert it into an internal Linked Data model.`

I am wondering what does that adapter do exactly? (Maybe an example?)
And what does the internal Linked Data model mean in the current context?
Thanks</div>

**Comment by jobulcke** [comment]
This have been resolved a while ago and the ticket was never closed
