### ISSUE TITLE
LDESClient should be able to parse large fragments efficiently

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#300]
This issue is the result from the following performance testing:
[Performance_test.xlsx](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/12422276/Performance_test.xlsx)

We noticed that larger fragments parse more slowly. Larger historical fragments could make it more efficient to host an LDES as less pages need to be traversed. However the LDESClient cannot handle very big fragments at the moment.

**Comment by Yalz** [comment]
As of now, the performance for this process is efficient enough. 
Further performance improvements will be tackled in dedicated stories
