### ISSUE TITLE
Need a model splitter

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#304]
When onboarding data publishers sometimes a single incoming message should produce multiple state objects, e.g. by using the SPARQL construct component only one model is created. The Version Creation component cannot handle these multiple state objects and only produces a version for one of the generated state objects.

What I propose is a simple state object splitter based on a rdf:type predicate search. 
* for CS we only need to search for all subjects for the configured object type: `?subject rdf:type ?configured-type`, group triples by subject and split that way
* for traffic counts we do the same but also take all triples recursively for the referred blank nodes and named nodes that exist in the message .. this will duplicate the commonly referred state objects

This algoritm may or may not in time result in Pieter's member splitting algorithm or something similar.

**Comment by xdxxxdx** [comment]
Good afternoon @rorlic @Tomvbe @Yalz  ,
I am wondering how this is implemented.  If it works for splitting a big graph by grouping the same subject (include recursive blank node), and output them one by one?
If yes, is there an example. 
Thanks.
