### ISSUE TITLE
Support redirects for the LdioHttpPoller

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#335]
The LdioHttpPoller currently  uses the RequestExecutor which was initially designed for the LDESClient who has custom redirect handling. The LdioHttpPoller has no custom redirect handling and will desire default redirect handling most of the time. 

We should provide a config parameter for this in the requestExecutor. Currently we configure this in the following two classes:

```
ClientCredentialsConfig -> RequestConfig.custom().setRedirectsEnabled(false).build();
DefaultConfig -> HttpClientBuilder.create().setDefaultHeaders(headers).disableRedirectHandling().build()
```

When creating a requestExecutor for the LdesClient, this should always be disabled but when making it for the httpPoller, it should always be enabled.

**Comment by Yalz** [comment]
@Tomvbe can you elaborate a bit more on how you would design this?

**Comment by Tomvbe** [comment]
> @Tomvbe can you elaborate a bit more on how you would design this?

I would use `setRedirectsEnabled(true)` for anything other than the LDESClient. You can probably remove it as true should be the default :smile: .

I am talking about the poller but this is the case for httpOut, poller, enricher, etc.

**Comment by Yalz** [comment]
To disable only for LDES Client the redirects
