### ISSUE TITLE
Custom headers on HTTP-Out

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/VSDS-Linked-Data-Interactions#359]
It would be nice to configure custom headers (e.g. API_KEY) on the HTTP-out connector.
This would allow to run LDIO integrations external from Urban Sense.

**Comment by Tomvbe** [comment]
We can resolve this issue by also using the 'request-executor' in this module

**Comment by Tomvbe** [comment]
@brechtvdv do you only need this for the api key or for other custom headers as well?

I made a small change that makes it possible to add the following config for the api key:
