### ISSUE TITLE
Extend the JsonLdAdaptor to handle arrays

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#415]
**Is your feature request related to a problem? Please describe.**
Currently, the JsonLdAdapter can add a JSON-LD context to a JSON object to convert it to linked data.
If you try to send a JSON array then an error is logged in the log file: 
```
be.vlaanderen.informatievlaanderen.ldes.ldi.exceptions.ParseToJsonException: Could not parse string to JSON. String with value:
[ { object-1 }, ... , { object N } ]
Cause: Not a JSON object START: [LBRACKET]
	at be.vlaanderen.informatievlaanderen.ldes.ldi.JsonToLdAdapter.translateJsonToLD(JsonToLdAdapter.java:57) ~[ldio-json-to-ld-adapter-jar-with-dependencies.jar:na]

```

**Describe the solution you'd like**
Please allow for JSON arrays. If an array is received, split the message automatically in its objects, adding the JSON-LD context to each array element (which should be an object) and push it into the pipeline.

**Comment by jeflaenen** [comment]
https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-1082 has been logged for this on the JIRA backlog, therefor this ticket will be closed.
