### ISSUE TITLE
Add support for prebound values in Sparql construct component

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#426]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to use some constants in a sparql construct query/constuct but you do not really want to hard code it, e.g. a base URL of some API, etc.

**Describe the solution you'd like**
Can you provide support for prebound values as defined [here](https://jena.apache.org/documentation/query/manipulating_sparql_using_arq.html) in the [SparqlConstructTransformer](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/core/ldi-transformers/sparql-construct)?
Ideally there is the possibility to define a prebound collection of key/value pairs in the transformer config.
Because it is possible to use environment variables in the application.yml file defining a workbench pipeline, it becomes possible to even use environment variables from outside the container running the workbench.

**Describe alternatives you've considered**
The only other option is hard-coding the invariants.

**Comment by rorlic** [comment]
There is one alternative/workaround:
- define an environment variable in the docker compose file with or without a default (pass in at runtime)
- in the pipeline add a sparql construct adding a sparql variable to the model based on the environment variable

**Example**
docker compose file:
```yaml
    environment:
      - API_BASE=${API_BASE:-https://example.com/api/v1}
      - SOMETHING_ELSE=${SOMETHING_ELSE:-anything}
```
workbench pipeline:
```yaml
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: |
              PREFIX : <https://example.com#>
              CONSTRUCT { 
                ?dummy :api ?api ; :myVariable ?somethingElse. 
              } WHERE { 
                bind(bnode() as ?dummy). 
                bind("${API_BASE}" as ?api) . 
                bind("${SOMETHING_ELSE}" as ?somethingElse) . 
              }
            infer: true
```

**Comment by Yalz** [comment]
Workaround in place. Feature no longer needed
