### ISSUE TITLE
Add a custom adapter to support Apache ActiveMQ

### ISSUE THREAD

**Issue by MPParsley** [Informatievlaanderen/VSDS-Linked-Data-Interactions#457]
**Is your feature request related to a problem? Please describe.**
A lot of data is available on Apache ActiveMQ but it requires custom adapters to consume this.

**Describe the solution you'd like**
A new input adapter for ldio that can connect to a given AMQ, credentials, topic/queue is requested.

**Describe alternatives you've considered**
Refactoring the producers would be an option but this would have a big impact on planning.
Writing a custom consumer that serves as an adapter would work but this would not be a reusable solution.
Using the current LdioHttpIn plugin would only work for those solutions that also offer an API.

**Additional context**
This solution would be similar to the Kafka adapter.

**Comment by jeflaenen** [comment]
Hi @MPParsley, we have created a ticket in our development backlog and we will take this up in one of the following sprints.

**Comment by MPPlexor** [comment]
Support for AMQP was added in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/498.

Thank you very much @jeflaenen, you may close this issue!
