### ISSUE TITLE
Add troubleshoot documentation based on faq

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#460]
We have some recurring questions from early adopters. Maybe we should add some troubleshooting documentation where we can document these solutions?

For example: work arounds for invalid certificates https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/458

**Comment by Yalz** [comment]
Wouldn't go into too much detail concerning certs, ... but for basic LDIO issues, sure

**Comment by MPParsley** [comment]
The solution in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/458#issuecomment-1898561432 is for docker compose, it would be nice to have a link to a more generic approach (that also works on kubernetes f.i.).

**Comment by dhaemer** [comment]
After the cert file is mounted, we can pass the cert file (and password) through the remote-url):
`remote-url: amqps://remote-amq-server:61617?initialReconnectDelay=100?jms.watchTopicAdvisories=false&transport.trustStoreLocation=/tmp/your-cert.ts&transport.trustStorePassword=changeit
`

**Comment by jobulcke** [comment]
Is not something we plan to do in the near future
