### ISSUE TITLE
Can not pass scope to LDIO Http Requester

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#477]
**Describe the bug**
Some identity systems (e.g. [Microsoft](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret)) require a `scope` parameter when requesting a token and if not given fail to return an OAuth2 access token. Please add the possibility to add a scope value (a string, can contain a list of scopes separated by a blank) for those identity providers that need it.

**Comment by Yalz** [comment]
@Tomvbe can you close if issue is resolved?
