### ISSUE TITLE
Cannot delete the configured pipeline : "title":"Bad Request","status":400,

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#527]
**Describe the bug**
Cannot delete the configured pipeline: ldes/ldi-orchestrator:2.1.0-SNAPSHOT

**Prerequisites:**
1. ldes/ldi-orchestrator:2.1.0-SNAPSHOT is up and running 
2. Run `curl --location 'http://localhost:8081/admin/api/v1/pipeline'`
Got:
 ```
[
    {
        "name": "my-first-pipeline",
        "status": "RUNNING",
        "updateSource": "AUTO",
        "description": null,
        "input": {
            "name": "Ldio:HttpIn",
            "adapter": {
                "name": "Ldio:RdfAdapter",
                "config": {}
            },
            "config": {}
        },
        "transformers": [],
        "outputs": [
            {
                "name": "Ldio:ConsoleOut",
                "config": {}
            }
        ]
    }
]
```
my-first-pipeline is configured 

**To Reproduce**

1. run ` curl --location --request DELETE 'http://localhost:8081/admin/api/v1/pipeline/my-first-pipeline'
`
As explained at [https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/pipeline-management/pipeline-api#deleting-a-pipeline](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/pipeline-management/pipeline-api#deleting-a-pipeline)

**Expected behavior**
my-first-pipeline is deleted

**Current behavior**
{"type":"about:blank","title":"Bad Request","status":400,"detail":"Failed to read request","instance":"/admin/api/v1/pipeline/my-first-pipeline"}

![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/d189c468-97fe-40ea-afe5-f60554c81ab5)
my-first-pipeline is still there

**Comment by Tomvbe** [comment]
This is because the DELETE expects a body.  @Yalz  told me this was meant to be a requestparam instead of a body. We should change this. This will fix the above bug.

![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/34196062/5b11b6f1-9a66-4399-a190-774560372161)

**Comment by Tomvbe** [comment]
I noticed, the reason for existence of this body is invalid. This has been implemented all over LDIO just to be able to keep state in the client which is already set through ldes client configuration. We should not change this with a requestParam but remove this option from the deletePipeline flow and use the config property in the client instead..
