### ISSUE TITLE
Publish individual NARs as assets on release

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-Linked-Data-Interactions#549]
**Is your feature request related to a problem? Please describe.**
NARs are published as part of the docker image, yet users that have a NiFi (clustered) installation want to use the NARs as standalone packages.

**Describe the solution you'd like**
Upload the NARs as part of the release package.

**Comment by Yalz** [comment]
Do you want to have this instead of the NiFi image or next to?

**Comment by jobulcke** [comment]
Resolved in #597
