### ISSUE TITLE
Ldio:RepositoryMaterialiser: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.shutdown()" because "this.scheduledExecutorService" is null

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#552]
**tags**: Sprint 48

> [VSDS-LDESServer4J](https://hub.docker.com/r/ldes/ldes-server/tags) 
> 
> revision: [edd4232da9c5051bffc716e77f4c668d9f5e3488](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/edd4232da9c5051bffc716e77f4c668d9f5e3488)
> 
> tag: [ldes/ldes-server: 2.11.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)
> 
> [VSDS-Linked-Data-Interactions](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions)
> 
> revision:  [2a0c95075e095e51969756ff26b1062abbdf26b3](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/commit/2a0c95075e095e51969756ff26b1062abbdf26b3) 
> 
> [ldi-workbench-nifi](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) tag: [ldes/ldi-workbench-nifi:2.2.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) 
> 
> [ldi-orchestrator](https://hub.docker.com/r/ldes/ldi-orchestrator/tags) tag: [ldes/ldi-orchestrator:2.2.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-orchestrator/tags)

**Describe the bug**
Cypress test-024 -  workbench.materialisation.feature  returns error
https://github.com/xdxxxdx/VSDS-LDES-E2E-testing/actions/runs/8360436381/job/22923959125 

**To Reproduce**
1. Follow the step by step test: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/024.workbench-materialize-to-rdf4j

**Current behavior**
When posting data to lido pipeline, we can see error:
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/dcd26566-552d-4118-8acb-1c82fa7e89b0)

**Full docker trace**
[rdf4j.txt](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/14693767/rdf4j.txt)

**Comment by Tomvbe** [comment]
Fixed in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/553
