### ISSUE TITLE
LdesDiscoverer should be able to use all capabilities of the RequestExecutor

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#561]
Currently the discoverer is configured with a default NoAuthExecutor. 
This means that you cannot use the features described in https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-core/ldio-http-requester.

To make it possible to discover secured flows, pass custom headers, have rate limiting, etc. we should make it possible to use a fully configured RequestExecutor in the disoverer.

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/586
