### ISSUE TITLE
Doc: Typo, observedAt

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#566]
https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/blob/3d491367d1fd2ca7c3a4e3c64bbec4d56e2380ca/docs/_ldio/ldio-transformers/ldio-version-object-creator.md?plain=1#L20

Here should be `generatedAt` instead of `observedAt` ?
Thanks

**Comment by jobulcke** [comment]
Has been resolved a while ago, ticket was never closed
