### ISSUE TITLE
be.vlaanderen.informatievlaanderen - ldes-client-processor is recogonized as an invalid processor for ldi-workbench-nifi:20230314T083305

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#60]
**Prerequisites:**

- Use the docker tags for VSDS sprint 22 UAT tests provided by @Yalz .
- LDI_WORKBENCH_NIFI_TAG=20230314T083305
- Test scenario: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gipod/1.replicate-ldes
- ldi-workbench-nifi is up and running on the port 8000

**Scenario:**
Upload NIFI workflow: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/1.replicate-ldes/nifi-workflow.json

**Current result:**
LdesClient 1.0-SNAPSHOT is Invalid
Please see:
![image](https://user-images.githubusercontent.com/15314807/226584342-c5102394-6967-44ba-9636-0b6df69b6e95.png)

**Expected result:**
LdesClient 1.0-SNAPSHOT should not be invalid

**Comment by rorlic** [comment]
Not applicable anymore: test https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/001.client-replicate-ldes has been rewritten using LDIO.
