### ISSUE TITLE
LdioLdesClient Handles 404 error without a crash

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#605]
[ldes/ldi-orchestrator:2.5.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/new?assignees=&labels=needs+triage&projects=&template=feature_request.md&title=#)

In the test, the client crashes with a 404 error with max retry reached.
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/f45c8f74-7156-415d-b358-e2ef460eec17)

I think there should be a way to allow 
1. The client doesn't crash, as the stream can be back online. e.g. halt this pipeline instead of crash it, with a notification message saying that the stream is not available, the pipeline is paused.
3. better logging instead of a raw crash message.

Thanks

**Comment by xdxxxdx** [comment]
> As discussed with the developers, the proposed solution of @xdxxxdx will be implemented when picking up this issue

@jobulcke, thanks. Please also make sure there is doc regarding this "fallback" behavior.
might be also worth to have a look possible  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes, to have a more robustic products, and integrate the test to unite testing (try out some unhappy paths).

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/621
