### ISSUE TITLE
Add INFO logging for state changes

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-Linked-Data-Interactions#609]
Currently, the [PipelineStatusService](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/blob/main/ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/services/PipelineStatusService.java) only logs a WARN (`Non initialized pipeline received status update`) when creating & uploading a new pipeline (which is BTW weird!). Nothing else gets logged.

In a production environment I want to know if a pipeline status is changed in order to monitor this with tooling. 
Please add INFO logging when state changes occur explicitly (admin mgmt) and implicitly (created, crashed, etc).

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/621
