### ISSUE TITLE
NgsiV2ToLdTranslatorProcessor 1.0.2-SNAPSHOT is recogonized as an invalid processor for ldi-workbench-nifi:20230314T083305

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#61]
**Prerequisites:**

- Use the docker tags for VSDS sprint 22 UAT tests provided by @Yalz .
- LDI_WORKBENCH_NIFI_TAG=20230314T083305
- Test scenario: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld
- ldi-workbench-nifi is up and running on the port 8000

**Scenario:**
Upload NIFI workflow: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld/nifi-workflow.json

**Current result:**
NgsiV2ToLdTranslatorProcessor 1.0.2-SNAPSHOT is Invalid
Please see:
![image](https://user-images.githubusercontent.com/15314807/226613870-e0c74097-09a9-49ad-9b61-7f8b357a9099.png)

**Expected result:**
NgsiV2ToLdTranslatorProcessor 1.0.2-SNAPSHOT should not be invalid

**Comment by rorlic** [comment]
Not applicable anymore: test has been removed because it was not a E2E test.

**Comment by xdxxxdx** [comment]
Hello, 
As discussed with @rorlic,

Closing current case requires the 1 to 1 mapping of the nifi processors tests are there.

this means the tests:
https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-623 (manual test)
https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-624 (automatic test)
are there, and the processors are working.

Thanks

**Comment by xdxxxdx** [comment]
Validated with the [ldi-workbench-nifi](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pkgs/container/ldi-workbench-nifi) tag: [20230508T085634](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pkgs/container/ldi-workbench-nifi/91437872?tag=20230508T085634)

With: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/031.nifi-workbench-components
Version: NgsiV2ToLdProcessor 0.0.1-SNAPSHOT
