### ISSUE TITLE
Ldio:LdesClientConnector documentation contains broken links

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-Linked-Data-Interactions#613]
**Describe the bug**
The [LDIO Client connector](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-inputs/ldio-ldes-client-connector) contains some dead links towards the LDES Client. 

To rework and integrate LDES Client documention in this page too (or refer to LDIO LDES Client)

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/616
