### ISSUE TITLE
Make it possible to allow multiple member-types in a single transformer

### ISSUE THREAD

**Issue by razoreater** [Informatievlaanderen/VSDS-Linked-Data-Interactions#651]
**Is your feature request related to a problem? Please describe.**

After creating new pipeline, if we want to transform data before posting it on an LDES stream, we are currently limited to transforming data for only one specific membertype. If the data does not align with this membertype, the posting process fails. 

For a current project, we are utilizing a vocabularium with multiple member-types required, and creating individual pipelines for each type is proving to be inefficient. [Link to the vocabularium](https://data.vlaanderen.be/ns/openbaardomein/infrastructuur)

**Describe the solution you'd like**

I believe it would be beneficial to have the capability to include multiple membertypes (e.g., in an array) or multiple transformers within the same pipeline.

**Describe alternatives you've considered**

One alternative would be to set up multiple pipelines, however, this approach adds unnecessary overhead.

**Comment by jeflaenen** [comment]
JIRA ticket VSDSPUB-1387 is created for this, so we can take this up in our sprint planning.
