### ISSUE TITLE
Relation 'treenoderecordentity' does not exist

### ISSUE THREAD

**Issue by SBylemans** [Informatievlaanderen/VSDS-Linked-Data-Interactions#676]
**Describe the bug**
When starting the LdesClientProcessor with a Postgres DB configured and keepState property to true, the processor produces an error with the error message: 
```
org.postgresql.util.PSQLException: ERROR: Relation 'treenoderecordentity' does not exist
```

**To Reproduce**
Configure LDESClientProcessor with Postgres DB for state, and set keepState property to true before first start of processor.

**Expected behavior**
LDESClientProcessor creates tables and runs as expected.

**Screenshots**
<img width="1063" alt="afbeelding" src="https://github.com/user-attachments/assets/1b4fefb3-cba9-4706-8f2d-1282587af911">

**Info**
Using version 2.3.0 of the processors.

**Workaround**
Start flow first time with keepState to false.

**Comment by jobulcke** [comment]
This will be verified when #663 has been solved

**Comment by jobulcke** [comment]
Hi @SBylemans 
I tried to reproduce this bug, but I did not succeed at it. This is the [flow definition](https://github.com/user-attachments/files/17905756/NiFi_Flow.3.json) I used. 
I also noticed you are using LdesClientProcesser 2.3.0.**_5_**-SNAPSHOT, but we never released such version
